package cn.reebtech.repoms.model.greendao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 17): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 17;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        AssetClsctDao.createTable(db, ifNotExists);
        AssetsDao.createTable(db, ifNotExists);
        DepartmentDao.createTable(db, ifNotExists);
        IDGeneratorDao.createTable(db, ifNotExists);
        LastLoginDao.createTable(db, ifNotExists);
        LocationDao.createTable(db, ifNotExists);
        Order_InDao.createTable(db, ifNotExists);
        Order_InvtDao.createTable(db, ifNotExists);
        Order_Invt_DetailDao.createTable(db, ifNotExists);
        Order_In_DetailDao.createTable(db, ifNotExists);
        Order_OutDao.createTable(db, ifNotExists);
        Order_Out_DetailDao.createTable(db, ifNotExists);
        Order_ReqDao.createTable(db, ifNotExists);
        Order_Req_DetailDao.createTable(db, ifNotExists);
        Order_RetDao.createTable(db, ifNotExists);
        Order_Ret_DetailDao.createTable(db, ifNotExists);
        ServerDao.createTable(db, ifNotExists);
        StacodeDao.createTable(db, ifNotExists);
        UserDao.createTable(db, ifNotExists);
        WareHouseDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        AssetClsctDao.dropTable(db, ifExists);
        AssetsDao.dropTable(db, ifExists);
        DepartmentDao.dropTable(db, ifExists);
        IDGeneratorDao.dropTable(db, ifExists);
        LastLoginDao.dropTable(db, ifExists);
        LocationDao.dropTable(db, ifExists);
        Order_InDao.dropTable(db, ifExists);
        Order_InvtDao.dropTable(db, ifExists);
        Order_Invt_DetailDao.dropTable(db, ifExists);
        Order_In_DetailDao.dropTable(db, ifExists);
        Order_OutDao.dropTable(db, ifExists);
        Order_Out_DetailDao.dropTable(db, ifExists);
        Order_ReqDao.dropTable(db, ifExists);
        Order_Req_DetailDao.dropTable(db, ifExists);
        Order_RetDao.dropTable(db, ifExists);
        Order_Ret_DetailDao.dropTable(db, ifExists);
        ServerDao.dropTable(db, ifExists);
        StacodeDao.dropTable(db, ifExists);
        UserDao.dropTable(db, ifExists);
        WareHouseDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AssetClsctDao.class);
        registerDaoClass(AssetsDao.class);
        registerDaoClass(DepartmentDao.class);
        registerDaoClass(IDGeneratorDao.class);
        registerDaoClass(LastLoginDao.class);
        registerDaoClass(LocationDao.class);
        registerDaoClass(Order_InDao.class);
        registerDaoClass(Order_InvtDao.class);
        registerDaoClass(Order_Invt_DetailDao.class);
        registerDaoClass(Order_In_DetailDao.class);
        registerDaoClass(Order_OutDao.class);
        registerDaoClass(Order_Out_DetailDao.class);
        registerDaoClass(Order_ReqDao.class);
        registerDaoClass(Order_Req_DetailDao.class);
        registerDaoClass(Order_RetDao.class);
        registerDaoClass(Order_Ret_DetailDao.class);
        registerDaoClass(ServerDao.class);
        registerDaoClass(StacodeDao.class);
        registerDaoClass(UserDao.class);
        registerDaoClass(WareHouseDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
