package cn.reebtech.repoms.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.reebtech.repoms.model.entity.IDGenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IDGENERATOR".
*/
public class IDGeneratorDao extends AbstractDao<IDGenerator, Long> {

    public static final String TABLENAME = "IDGENERATOR";

    /**
     * Properties of entity IDGenerator.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property Date = new Property(2, java.util.Date.class, "date", false, "DATE");
        public final static Property Curnum = new Property(3, int.class, "curnum", false, "CURNUM");
    }


    public IDGeneratorDao(DaoConfig config) {
        super(config);
    }
    
    public IDGeneratorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IDGENERATOR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TYPE\" TEXT NOT NULL ," + // 1: type
                "\"DATE\" INTEGER NOT NULL ," + // 2: date
                "\"CURNUM\" INTEGER NOT NULL );"); // 3: curnum
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_IDGENERATOR__id_DESC ON \"IDGENERATOR\"" +
                " (\"_id\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IDGENERATOR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IDGenerator entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getType());
        stmt.bindLong(3, entity.getDate().getTime());
        stmt.bindLong(4, entity.getCurnum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IDGenerator entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getType());
        stmt.bindLong(3, entity.getDate().getTime());
        stmt.bindLong(4, entity.getCurnum());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public IDGenerator readEntity(Cursor cursor, int offset) {
        IDGenerator entity = new IDGenerator( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // type
            new java.util.Date(cursor.getLong(offset + 2)), // date
            cursor.getInt(offset + 3) // curnum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IDGenerator entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setType(cursor.getString(offset + 1));
        entity.setDate(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setCurnum(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IDGenerator entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IDGenerator entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IDGenerator entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
