package cn.reebtech.repoms.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.reebtech.repoms.model.entity.Order_Invt_Detail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER__INVT__DETAIL".
*/
public class Order_Invt_DetailDao extends AbstractDao<Order_Invt_Detail, Long> {

    public static final String TABLENAME = "ORDER__INVT__DETAIL";

    /**
     * Properties of entity Order_Invt_Detail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Order = new Property(1, String.class, "order", false, "ORDER");
        public final static Property Asset = new Property(2, String.class, "asset", false, "ASSET");
        public final static Property Completed = new Property(3, boolean.class, "completed", false, "COMPLETED");
        public final static Property Uploaded = new Property(4, boolean.class, "uploaded", false, "UPLOADED");
    }


    public Order_Invt_DetailDao(DaoConfig config) {
        super(config);
    }
    
    public Order_Invt_DetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER__INVT__DETAIL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ORDER\" TEXT NOT NULL ," + // 1: order
                "\"ASSET\" TEXT NOT NULL ," + // 2: asset
                "\"COMPLETED\" INTEGER NOT NULL ," + // 3: completed
                "\"UPLOADED\" INTEGER NOT NULL );"); // 4: uploaded
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_ORDER__INVT__DETAIL__id_DESC ON \"ORDER__INVT__DETAIL\"" +
                " (\"_id\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER__INVT__DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Order_Invt_Detail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrder());
        stmt.bindString(3, entity.getAsset());
        stmt.bindLong(4, entity.getCompleted() ? 1L: 0L);
        stmt.bindLong(5, entity.getUploaded() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Order_Invt_Detail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrder());
        stmt.bindString(3, entity.getAsset());
        stmt.bindLong(4, entity.getCompleted() ? 1L: 0L);
        stmt.bindLong(5, entity.getUploaded() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Order_Invt_Detail readEntity(Cursor cursor, int offset) {
        Order_Invt_Detail entity = new Order_Invt_Detail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // order
            cursor.getString(offset + 2), // asset
            cursor.getShort(offset + 3) != 0, // completed
            cursor.getShort(offset + 4) != 0 // uploaded
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Order_Invt_Detail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrder(cursor.getString(offset + 1));
        entity.setAsset(cursor.getString(offset + 2));
        entity.setCompleted(cursor.getShort(offset + 3) != 0);
        entity.setUploaded(cursor.getShort(offset + 4) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Order_Invt_Detail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Order_Invt_Detail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Order_Invt_Detail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
