package cn.reebtech.repoms.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.reebtech.repoms.model.entity.WaitBindAssets;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WAIT_BIND_ASSETS".
*/
public class WaitBindAssetsDao extends AbstractDao<WaitBindAssets, Long> {

    public static final String TABLENAME = "WAIT_BIND_ASSETS";

    /**
     * Properties of entity WaitBindAssets.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Pid = new Property(0, Long.class, "pid", true, "_id");
        public final static Property Id = new Property(1, String.class, "id", false, "ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Clsct = new Property(3, String.class, "clsct", false, "CLSCT");
        public final static Property Specification = new Property(4, String.class, "specification", false, "SPECIFICATION");
        public final static Property Manut = new Property(5, String.class, "manut", false, "MANUT");
        public final static Property Price = new Property(6, double.class, "price", false, "PRICE");
        public final static Property Indate = new Property(7, java.util.Date.class, "indate", false, "INDATE");
        public final static Property Lastupdate = new Property(8, java.util.Date.class, "lastupdate", false, "LASTUPDATE");
        public final static Property Status = new Property(9, String.class, "status", false, "STATUS");
        public final static Property Inbound = new Property(10, boolean.class, "inbound", false, "INBOUND");
        public final static Property Location = new Property(11, String.class, "location", false, "LOCATION");
        public final static Property Rfid = new Property(12, String.class, "rfid", false, "RFID");
        public final static Property Remark = new Property(13, String.class, "remark", false, "REMARK");
        public final static Property Asset_code = new Property(14, String.class, "asset_code", false, "ASSET_CODE");
    }


    public WaitBindAssetsDao(DaoConfig config) {
        super(config);
    }
    
    public WaitBindAssetsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WAIT_BIND_ASSETS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: pid
                "\"ID\" TEXT NOT NULL ," + // 1: id
                "\"NAME\" TEXT NOT NULL ," + // 2: name
                "\"CLSCT\" TEXT NOT NULL ," + // 3: clsct
                "\"SPECIFICATION\" TEXT," + // 4: specification
                "\"MANUT\" TEXT," + // 5: manut
                "\"PRICE\" REAL NOT NULL ," + // 6: price
                "\"INDATE\" INTEGER," + // 7: indate
                "\"LASTUPDATE\" INTEGER," + // 8: lastupdate
                "\"STATUS\" TEXT," + // 9: status
                "\"INBOUND\" INTEGER NOT NULL ," + // 10: inbound
                "\"LOCATION\" TEXT," + // 11: location
                "\"RFID\" TEXT," + // 12: rfid
                "\"REMARK\" TEXT," + // 13: remark
                "\"ASSET_CODE\" TEXT);"); // 14: asset_code
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_WAIT_BIND_ASSETS_ID ON \"WAIT_BIND_ASSETS\"" +
                " (\"ID\" ASC);");
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_WAIT_BIND_ASSETS_ID_DESC ON \"WAIT_BIND_ASSETS\"" +
                " (\"ID\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WAIT_BIND_ASSETS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WaitBindAssets entity) {
        stmt.clearBindings();
 
        Long pid = entity.getPid();
        if (pid != null) {
            stmt.bindLong(1, pid);
        }
        stmt.bindString(2, entity.getId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getClsct());
 
        String specification = entity.getSpecification();
        if (specification != null) {
            stmt.bindString(5, specification);
        }
 
        String manut = entity.getManut();
        if (manut != null) {
            stmt.bindString(6, manut);
        }
        stmt.bindDouble(7, entity.getPrice());
 
        java.util.Date indate = entity.getIndate();
        if (indate != null) {
            stmt.bindLong(8, indate.getTime());
        }
 
        java.util.Date lastupdate = entity.getLastupdate();
        if (lastupdate != null) {
            stmt.bindLong(9, lastupdate.getTime());
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(10, status);
        }
        stmt.bindLong(11, entity.getInbound() ? 1L: 0L);
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(12, location);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(13, rfid);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(14, remark);
        }
 
        String asset_code = entity.getAsset_code();
        if (asset_code != null) {
            stmt.bindString(15, asset_code);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WaitBindAssets entity) {
        stmt.clearBindings();
 
        Long pid = entity.getPid();
        if (pid != null) {
            stmt.bindLong(1, pid);
        }
        stmt.bindString(2, entity.getId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getClsct());
 
        String specification = entity.getSpecification();
        if (specification != null) {
            stmt.bindString(5, specification);
        }
 
        String manut = entity.getManut();
        if (manut != null) {
            stmt.bindString(6, manut);
        }
        stmt.bindDouble(7, entity.getPrice());
 
        java.util.Date indate = entity.getIndate();
        if (indate != null) {
            stmt.bindLong(8, indate.getTime());
        }
 
        java.util.Date lastupdate = entity.getLastupdate();
        if (lastupdate != null) {
            stmt.bindLong(9, lastupdate.getTime());
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(10, status);
        }
        stmt.bindLong(11, entity.getInbound() ? 1L: 0L);
 
        String location = entity.getLocation();
        if (location != null) {
            stmt.bindString(12, location);
        }
 
        String rfid = entity.getRfid();
        if (rfid != null) {
            stmt.bindString(13, rfid);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(14, remark);
        }
 
        String asset_code = entity.getAsset_code();
        if (asset_code != null) {
            stmt.bindString(15, asset_code);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WaitBindAssets readEntity(Cursor cursor, int offset) {
        WaitBindAssets entity = new WaitBindAssets( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // pid
            cursor.getString(offset + 1), // id
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // clsct
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // specification
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // manut
            cursor.getDouble(offset + 6), // price
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // indate
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // lastupdate
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // status
            cursor.getShort(offset + 10) != 0, // inbound
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // location
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // rfid
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // remark
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // asset_code
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WaitBindAssets entity, int offset) {
        entity.setPid(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.getString(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setClsct(cursor.getString(offset + 3));
        entity.setSpecification(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setManut(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setPrice(cursor.getDouble(offset + 6));
        entity.setIndate(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setLastupdate(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setStatus(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setInbound(cursor.getShort(offset + 10) != 0);
        entity.setLocation(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setRfid(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRemark(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAsset_code(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WaitBindAssets entity, long rowId) {
        entity.setPid(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WaitBindAssets entity) {
        if(entity != null) {
            return entity.getPid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WaitBindAssets entity) {
        return entity.getPid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
